services:
  jaeger:
    image: "jaegertracing/all-in-one:1.73"
    ports:
      - "14268:14268"
      - "16686:16686"

  redis:
    image: "redis:8.2"
    command: redis-server --port 6379
    restart: on-failure
    ports:
      - "6379:6379"
    environment:
      REDIS_REPLICATION_MODE: master
    volumes:
      - redis-data:/var/lib/redis


volumes:
  redis-data: