### To add a new note:

# curl --location --request POST 'localhost:8080/create'
#--header 'Content-Type: application/json'
#--data-raw '{
#    "title":"Something interesting",
#    "content": "Lorem ipsum..."
#}'
POST localhost:8080/create
Content-Type: application/json

{
  "title": "Something interesting",
  "content": "Lorem ipsum..."
}

> {% client.global.set("noteID", response.body.note_id); %}

### To get a new note:

# curl --location --request GET 'localhost:8080/get?note_id=7411ff79-fd1d-46ab-b9f8-21105cd770ce'
GET localhost:8080/get?note_id={{noteID}}

###

